// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4fM9u6lDXb62-csmjm_H5n2gi8KauhiE',
    appId: '1:174950692126:web:3958e2c56d37167aaa050f',
    messagingSenderId: '174950692126',
    projectId: 'fir-1771020729',
    authDomain: 'fir-1771020729.firebaseapp.com',
    storageBucket: 'fir-1771020729.firebasestorage.app',
    measurementId: 'G-SNJCEWG66M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7pWn2GL5Y5jeLKzm23KTIw7Eo8aBkIwA',
    appId: '1:174950692126:android:63b6eb89e2e5e458aa050f',
    messagingSenderId: '174950692126',
    projectId: 'fir-1771020729',
    storageBucket: 'fir-1771020729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Y3dpzLFDem9_UsnkemwBLsbz7_jgj0E',
    appId: '1:174950692126:ios:4567b370aa8c50c9aa050f',
    messagingSenderId: '174950692126',
    projectId: 'fir-1771020729',
    storageBucket: 'fir-1771020729.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1771020729',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Y3dpzLFDem9_UsnkemwBLsbz7_jgj0E',
    appId: '1:174950692126:ios:4567b370aa8c50c9aa050f',
    messagingSenderId: '174950692126',
    projectId: 'fir-1771020729',
    storageBucket: 'fir-1771020729.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1771020729',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4fM9u6lDXb62-csmjm_H5n2gi8KauhiE',
    appId: '1:174950692126:web:a1fbc59e2e44b378aa050f',
    messagingSenderId: '174950692126',
    projectId: 'fir-1771020729',
    authDomain: 'fir-1771020729.firebaseapp.com',
    storageBucket: 'fir-1771020729.firebasestorage.app',
    measurementId: 'G-9STCYKRGW4',
  );

}